meta_product_name: "StreetBusk"
meta_title: "StreetBusk - Live Performance Now"
meta_description: "Discover and support exciting street artists near you"
meta_image: "logo.png"
twitter_account: "@Alex_Wisowaty"